import React from 'react'
import { AlertCircle, BarChart3 } from 'lucide-react'
import toast from 'react-hot-toast'
import { secureStegAPI } from '../api/client'
import { useAppStore } from '../store'
import { UploadDropzone } from './UploadDropzone'

export const DetectMode = () => {
  const {
    detectFile,
    setDetectFile,
    detectSensitivity,
    setDetectSensitivity,
    detectionResult,
    setDetectionResult,
    isLoading,
    setIsLoading,
    error,
    setError,
  } = useAppStore()

  const handleDetect = async () => {
    if (!detectFile) {
      setError('Select an image file for analysis')
      return
    }

    setIsLoading(true)
    setError(null)

    try {
      const response = await secureStegAPI.detect(detectFile, detectSensitivity)
      setDetectionResult(response.data)
      toast.success('Analysis complete')
    } catch (err) {
      const message = err.response?.data?.detail || 'Detection analysis failed'
      setError(message)
      toast.error(message)
    } finally {
      setIsLoading(false)
    }
  }

  const analysis = detectionResult?.analysis

  return (
    <div className="space-y-6">
      <section className="grid gap-6 xl:grid-cols-[0.92fr_1.08fr]">
        <article className="panel space-y-5">
          <div className="section-heading">
            <h2 className="section-title">Analyze For Hidden Data</h2>
            <p className="section-copy">Drop an image and inspect anomaly signals generated by the detector pipeline.</p>
          </div>

          <UploadDropzone
            title="Drop image for analysis"
            description="Supports standard image formats used by the detector."
            file={detectFile}
            accept="image/*"
            onFileSelect={(file) => {
              setDetectFile(file)
              setDetectionResult(null)
              setError(null)
            }}
            kind="image"
            buttonLabel="Choose image"
          />

          <div className="subpanel">
            <h3 className="subpanel-title mb-3">Sensitivity</h3>
            <div className="grid grid-cols-3 gap-3">
              {['low', 'medium', 'high'].map((level) => (
                <button
                  key={level}
                  onClick={() => setDetectSensitivity(level)}
                  className={`choice-card ${detectSensitivity === level ? 'choice-card-active' : ''}`}
                >
                  <span className="choice-card__title capitalize">{level}</span>
                  <span className="choice-card__copy">
                    {level === 'low' && 'Few false positives'}
                    {level === 'medium' && 'Balanced detection'}
                    {level === 'high' && 'More aggressive flagging'}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {error && (
            <div className="alert alert-error">
              <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <button type="button" onClick={handleDetect} disabled={isLoading || !detectFile} className="btn-primary w-full justify-center">
            {isLoading ? 'Analyzing image...' : 'Analyze Image'}
          </button>
        </article>

        <article className="panel panel-compact space-y-4">
          <div className="section-heading">
            <h2 className="section-title">Analysis Result</h2>
            <p className="section-copy">Probability scoring and anomaly metrics are updated after detection.</p>
          </div>

          {analysis ? (
            <>
              <div className="subpanel">
                <div className="flex items-center gap-2 mb-4">
                  <BarChart3 className="w-5 h-5 text-[color:var(--accent)]" />
                  <h3 className="font-semibold">Probability Summary</h3>
                </div>

                <div className="flex items-center justify-between mb-2">
                  <span className="text-[color:var(--muted)]">Hidden data probability</span>
                  <span className="text-2xl font-bold text-[color:var(--accent)]">
                    {Math.round(analysis.probability * 100)}%
                  </span>
                </div>
                <div className="w-full h-3 bg-[color:var(--surface-muted)] rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-emerald-400 to-cyan-500 transition-all duration-500"
                    style={{ width: `${analysis.probability * 100}%` }}
                  />
                </div>
                <p className="text-sm text-[color:var(--muted)] mt-2">{analysis.recommendation}</p>
              </div>

              <div className="subpanel space-y-3">
                <h4 className="font-semibold">Anomaly Metrics</h4>

                <div>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm text-[color:var(--muted)]">LSB Distribution</span>
                    <span className="font-medium">{Math.round((analysis.detailed_analysis?.lsb_anomaly || 0) * 100)}%</span>
                  </div>
                  <div className="metric-bar"><div className="metric-bar__fill bg-sky-500" style={{ width: `${Math.min(100, (analysis.detailed_analysis?.lsb_anomaly || 0) * 100)}%` }} /></div>
                </div>

                <div>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm text-[color:var(--muted)]">Channel Correlation</span>
                    <span className="font-medium">{Math.round((analysis.detailed_analysis?.channel_anomaly || 0) * 100)}%</span>
                  </div>
                  <div className="metric-bar"><div className="metric-bar__fill bg-fuchsia-500" style={{ width: `${Math.min(100, (analysis.detailed_analysis?.channel_anomaly || 0) * 100)}%` }} /></div>
                </div>

                <div>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm text-[color:var(--muted)]">Entropy Shift</span>
                    <span className="font-medium">{Math.round((analysis.detailed_analysis?.entropy_anomaly || 0) * 100)}%</span>
                  </div>
                  <div className="metric-bar"><div className="metric-bar__fill bg-emerald-500" style={{ width: `${Math.min(100, (analysis.detailed_analysis?.entropy_anomaly || 0) * 100)}%` }} /></div>
                </div>
              </div>

              <div className={`status-banner ${analysis.hidden_data_detected ? 'status-banner-alert' : 'status-banner-safe'}`}>
                {analysis.hidden_data_detected ? 'Likely contains hidden data' : 'No strong hidden-data signal detected'}
              </div>
            </>
          ) : (
            <div className="empty-state">
              Run detection to view probability scoring, anomaly bars, and the final recommendation.
            </div>
          )}
        </article>
      </section>
    </div>
  )
}
